apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-demo
spec:
  restartPolicy: Never
  containers:
  - image: nginx
    name: nginx-container
    resources: {}
    volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html
  - image: ubuntu
    name: ubuntu-container
    command: ["/bin/sh"]
    args: ["-c", "echo 'Hello, World!!!' > /pod-data/index.html"]
    resources: {}
    volumeMounts:
      - name: shared-data
        mountPath: /pod-data
  volumes:
    - name: shared-data
      emptyDir: {}
