apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
    purpose: emptydir-demo
  name: emptydir-pod
spec:
  containers:
  - image: busybox
    name: container-1
    command: ["/bin/sh", "-c"]
    args: ["date >> /cache/date.txt; sleep 1000"]
    resources: {}
    volumeMounts:
      - name: cache-volume
        mountPath: /cache
  - image: busybox
    name: container-2
    command: ["/bin/sh", "-c"]
    args: ["cat /cache/date.txt; sleep 1000"]
    resources: {}
    volumeMounts:
      - name: cache-volume
        mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir: {}
