apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: init-demo-01
spec:
  initContainers:
    - image: alpine
      name: sleeper
      command: ["sleep", "10"]
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - name: http
      containerPort: 80
    resources: {}
