apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - image: nginx
    name: task-pv-container
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - name: task-pv-storage
        mountPath: /usr/share/nginx/html
    resources: {}

