apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Daniel Okoronkwo</title>
    </head>
    <body>
        <h1>Welcome to Daniel Okoronkwo Portfolio</h1>
        <p>Discover Valuable and Hands-On Software Development Articles</p>
        <div>https://www.danielokoronkwo.com</div>
    </body>
    </html>

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: config
        mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: Always
  volumes:
    - name: config
      configMap:
        name: nginx-html-cm

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: nginx
  type: NodePort