apiVersion: v1
data:
  BACKGROUND_COLOR: green
  TEXT_COLOR: white
kind: ConfigMap
metadata:
  name: app-config
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - /bin/sh
      - -c
      - env
    env:
      - name: BACKGROUND_COLOR
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: BACKGROUND_COLOR
      - name: TEXT_COLOR
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: TEXT_COLOR
    resources: {}
  restartPolicy: Never
