apiVersion: v1
data:
  BACKGROUND_COLOR: green
  TEXT_COLOR: white
kind: ConfigMap
metadata:
  name: app-config
---
apiVersion: v1
kind: Pod
metadata:
  name: go-app
  labels:
    app.kubernetes.io/name: go-app
spec:
  containers:
  - image: varsilias/go-ms:normal
    name: go-app
    env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
     app.kubernetes.io/name: go-app
  name: go-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app.kubernetes.io/name: go-app
  type: NodePort
