apiVersion: v1
kind: Service
metadata:
  name: go-headless
  labels:
    app: go
spec:
  clusterIP: None
  ports:
  - name: web
    port: 80
  selector:
    app: go
---
apiVersion: v1
kind: Service
metadata:
  name: go-normal
  labels:
    app: go
spec:
  ports:
  - name: web
    port: 80
  selector:
    app: go
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go
spec:
  serviceName: go-headless
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      containers:
      - image: varsilias/go-ms:normal
        name: go
        ports:
          - containerPort: 80
            name: web
        resources: {}
        volumeMounts:
          - name: www
            mountPath: /var/www
          - name: shared-volume
            mountPath: /var/www/shared
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 100Mi