apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  serviceAccountName: build-robot
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: Always
