apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: default
spec:
  selector:
    app: go-app
  type: NodePort 
  ports:
  - name: go-app
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - image: varsilias/go-ms:normal
        name: go-ms
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

