apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: disk
                operator: In
                values: ["ssd"]
          weight: 25
        - preference:
            matchExpressions:
              - key: disk
                operator: In
                values: ["hdd"]
          weight: 1 # 100 to make this the most preferred rule