apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              # - key: storageType
              #   operator: In
              #   values: ["ssd"]
              - key: disk
                operator: In
                values: ["ssd"]
          weight: 1