apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: core-read-only
  namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: core-read-only
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: core-read-only
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: daniel
