apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    env: uat
    user: nginx
  annotations:
    scrape: "true"
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
