apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox:latest
    name: busybox
    command:
      - /bin/sh
      - -c
      - |
        echo "POD NAME: $POD_NAME"
        echo "POD IP: $POD_IP"
        echo "POD NAMESPACE: $POD_NAMESPACE"
        echo "NODE IP: $NODE_IP"
        echo "POD IS RUNNING IN: $NODE_NAME"
    ports:
    - containerPort: 80
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    resources: {}
