# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     run: command-demo
#   name: command-demo
# spec:
#   containers:
#   - image: debian
#     name: command-demo-container
#     command:
#     - printenv
#     args:
#     - HOSTNAME
#     - KUBERNETES_PORT
#     resources:
#       requests:
#         cpu: 100m
#         memory: 64Mi
#       limits:
#         cpu: 100m
#         memory: 128Mi
#   dnsPolicy: ClusterFirst
#   restartPolicy: Always
# ---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dummy
  name: dummy
spec:
  containers:
  - image: ubuntu
    name: dummy-container
    command:
    - '/bin/sh'
    - '-c'
    args:
    - 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done'
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never