apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent # Other options include: Never, Always
    name: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: myregistry.com-pull-secrets # can be named anything provided it also matches the name of an actual secret in your cluster
  restartPolicy: Always
status: {}
