apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
  DB_PASSWORD: YWRtaW4xMjM=
  DB_USER: cm9vdA==
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - /bin/echo
    args: ["$(DB_USERNAME)"]
    env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB_PASSWORD
    resources: {}
  restartPolicy: Never
