apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  DB_PASSWORD: YWRtaW4xMjM=
  DB_USER: cm9vdA==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
    resources: {}
  restartPolicy: Never
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret