apiVersion: v1
kind: Secret
metadata:
  name: nginx-cm
type: Opaque
stringData:
  custom-nginx.conf: |
    server {
        listen       8080
        server_name  ""
        location / {
            root    /usr/share/nginx/html
            index   index.html index.htm
        }
    }
