apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr-2
    image: vish/stress
    args:
      - -cpus
      - "2"
    resources:
      requests:
        cpu: "100"
      limits:
        cpu: "100"