apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
     - default: 
        cpu: 1
       defaultRequest: 
        cpu: "0.5"
       type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limits
spec:
  limits:
    - max: 
        storage: 2Gi
      min: 
        storage: 1Gi 
      type: PersistentVolumeClaim

